CREATE TABLE IF NOT EXISTS entities (
                                        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        callsign       VARCHAR(255),
    icao_hex       VARCHAR(255),
    metadata       VARCHAR(255),
    type           VARCHAR(255),
    classification VARCHAR(255),
    CONSTRAINT ukso01xny7xho1fk68noknl9so6 UNIQUE (icao_hex)
    );

CREATE TABLE IF NOT EXISTS events (
                                      id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      altitude  DOUBLE PRECISION,
                                      entity_id BIGINT NOT NULL,
                                      heading   DOUBLE PRECISION,
                                      lat       DOUBLE PRECISION,
                                      lon       DOUBLE PRECISION,
                                      speed     DOUBLE PRECISION,
                                      timestamp TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS baselines (
                                         id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         avg_altitude  DOUBLE PRECISION,
                                         avg_heading   DOUBLE PRECISION,
                                         avg_lat       DOUBLE PRECISION,
                                         avg_lon       DOUBLE PRECISION,
                                         avg_speed     DOUBLE PRECISION,
                                         calculated_at TIMESTAMPTZ,
                                         event_count   INTEGER,
                                         entity_id     BIGINT NOT NULL,
                                         CONSTRAINT uko0ykets94u5x5ek89dvnagy57 UNIQUE (entity_id),
    CONSTRAINT fkargeky4wv13g2g164k6wvxh82 FOREIGN KEY (entity_id) REFERENCES entities(id)
    );

CREATE TABLE IF NOT EXISTS anomalies (
                                         id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         explanation VARCHAR(255),
    flagged_at  TIMESTAMPTZ,
    score       DOUBLE PRECISION,
    entity_id   BIGINT NOT NULL,
    event_id    BIGINT NOT NULL,
    CONSTRAINT fkl01eeg4l9jikvcle8jfu6k43v FOREIGN KEY (entity_id) REFERENCES entities(id),
    CONSTRAINT fkaqn0d4l81ypci33egexa4effw FOREIGN KEY (event_id) REFERENCES events(id)
    );

CREATE TABLE IF NOT EXISTS users (
                                     id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     password VARCHAR(255) NOT NULL,
    role     VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
    CONSTRAINT users_role_check CHECK (role IN ('ANALYST', 'OPERATOR', 'ADMIN'))
    );

ALTER TABLE events
    ADD CONSTRAINT fk_events_entity FOREIGN KEY (entity_id) REFERENCES entities(id);